name: Html User Guide

on:
  push:
    paths:
      - README.md

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3  # Go to branch repository
      - uses: docker://pandoc/latex:latest
        with:
          args: >-  # allows you to break string into multiple lines
            --from markdown+implicit_figures 
            --to html5 
            --metadata title="Dcs5 Controller" 
            --metadata author="jerome.guay@dfo.mpo.gc.ca" 
            --metadata date="May 2023" 
            --highlight-style=tango 
            -V colorlinks=True 
            -V linkcolor=red 
            -V urlcolor=blue 
            --toc
            --output=user_guide_en.html README.md
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Converting README.md to HTML"
          git push
