name: Translate README

on: push
#on:
#  push:
#    branches:
#      - not_a_branch

jobs:
  Translate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Adding README - French
        uses: dephraiim/translate-readme@main
        with:
          LANG: fr

